-- Empty database schema extracted from bin-service Flyway migration V1__init.sql.

CREATE TABLE bin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(128),
    volume INTEGER,
    coord_x NUMERIC(12, 2) NOT NULL,
    coord_y NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uc_bin_coord UNIQUE (coord_x, coord_y)
);

CREATE TABLE vehicle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_plate VARCHAR(32) NOT NULL
);

CREATE UNIQUE INDEX ux_vehicle_license_plate_norm
    ON vehicle (lower(btrim(license_plate)));

CREATE TABLE tour (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    vehicle_id BIGINT NOT NULL,
    CONSTRAINT fk_tour_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)
);

CREATE INDEX idx_tour_active ON tour (ended_at) WHERE ended_at IS NULL;

CREATE TABLE nfc_tag_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid VARCHAR(64) NOT NULL,
    bin_id BIGINT NOT NULL,
    mapped_at TIMESTAMPTZ NOT NULL,
    unmapped_at TIMESTAMPTZ,
    CONSTRAINT fk_nfc_tag_mapping_bin FOREIGN KEY (bin_id) REFERENCES bin (id)
);

CREATE UNIQUE INDEX ux_nfc_tag_mapping_uid_active
    ON nfc_tag_mapping (uid)
    WHERE unmapped_at IS NULL;

CREATE INDEX idx_nfc_tag_mapping_uid_mapped_at_desc
    ON nfc_tag_mapping (uid, mapped_at DESC);

CREATE INDEX idx_nfc_tag_mapping_bin_active
    ON nfc_tag_mapping (bin_id)
    WHERE unmapped_at IS NULL;

CREATE TABLE bin_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bin_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL,
    activity_timestamp TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_bin_activity_bin FOREIGN KEY (bin_id) REFERENCES bin (id)
);

CREATE INDEX idx_bin_activity_bin_id_ts ON bin_activity (bin_id, activity_timestamp DESC);

CREATE TABLE bin_visit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_event_id VARCHAR(64) NOT NULL,
    event_timestamp TIMESTAMPTZ NOT NULL,
    received_timestamp TIMESTAMPTZ NOT NULL,
    connectivity_state VARCHAR(32) NOT NULL,
    fill_level VARCHAR(32) NOT NULL,
    action VARCHAR(32) NOT NULL,
    tour_id BIGINT NOT NULL,
    nfc_tag_mapping_id BIGINT,
    CONSTRAINT uc_bin_visit_client_event_id UNIQUE (client_event_id),
    CONSTRAINT fk_bin_visit_tour FOREIGN KEY (tour_id) REFERENCES tour (id),
    CONSTRAINT fk_bin_visit_nfc_tag_mapping FOREIGN KEY (nfc_tag_mapping_id) REFERENCES nfc_tag_mapping (id)
);

CREATE TABLE vehicle_emptying (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_timestamp TIMESTAMPTZ NOT NULL,
    received_timestamp TIMESTAMPTZ NOT NULL,
    client_event_id VARCHAR(64) NOT NULL,
    connectivity_state VARCHAR(32) NOT NULL,
    tour_id BIGINT NOT NULL,
    CONSTRAINT uc_vehicle_emptying_client_event_id UNIQUE (client_event_id),
    CONSTRAINT fk_vehicle_emptying_tour FOREIGN KEY (tour_id) REFERENCES tour (id)
);

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    password_hash VARCHAR(200) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX ux_user_account_username_norm
    ON user_account (lower(btrim(username)));
